/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BackfillRunCompletions {
  backfillRunId: string;
  createdAt: Generated<string>;
  fetchedMessageCount: number;
  id: string;
  storedMessageCount: number;
}

export interface BackfillRunFailures {
  backfillRunId: string;
  createdAt: Generated<string>;
  errorMessage: string;
  id: string;
}

export interface BackfillRunProgress {
  backfillRunId: string;
  createdAt: Generated<string>;
  fetchedMessageCount: number;
  id: string;
  storedMessageCount: number;
}

export interface BackfillRuns {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface BookmarkAdditions {
  createdAt: Generated<string>;
  id: string;
  messageId: string;
  source: string;
}

export interface BookmarkRemovals {
  createdAt: Generated<string>;
  id: string;
  messageId: string;
  source: string;
}

export interface BookmarkSnoozes {
  createdAt: Generated<string>;
  id: string;
  messageId: string;
  until: string;
}

export interface ChannelCategoryChanges {
  category: string;
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface ChannelCategoryClearings {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface ChannelDetailRevisions {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
  isThread: number;
  name: string;
}

export interface ChannelPositionChanges {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
  position: number;
}

export interface ChannelPositionClearings {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface ChannelRemovals {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface Channels {
  createdAt: Generated<string>;
  discordChannelId: string;
  guildId: string;
  id: string;
}

export interface ChannelTopicChanges {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
  topic: string;
}

export interface ChannelTopicClearings {
  channelId: string;
  createdAt: Generated<string>;
  id: string;
}

export interface GatewayConnections {
  createdAt: Generated<string>;
  id: string;
}

export interface GatewayDisconnections {
  createdAt: Generated<string>;
  id: string;
}

export interface GatewayHeartbeats {
  createdAt: Generated<string>;
  id: string;
}

export interface Guilds {
  createdAt: Generated<string>;
  discordGuildId: string;
  id: string;
}

export interface MemberDetailRevisions {
  createdAt: Generated<string>;
  displayName: string;
  id: string;
  memberId: string;
  username: string;
}

export interface Members {
  createdAt: Generated<string>;
  discordUserId: string;
  id: string;
}

export interface MessageDeletions {
  createdAt: Generated<string>;
  id: string;
  messageId: string;
}

export interface MessageRevisions {
  content: string;
  createdAt: Generated<string>;
  id: string;
  messageId: string;
}

export interface Messages {
  authorMemberId: string;
  channelId: string;
  createdAt: Generated<string>;
  discordCreatedAt: string;
  discordMessageId: string;
  id: string;
}

export interface MessageSendDeliveries {
  createdAt: Generated<string>;
  discordMessageId: string;
  id: string;
  messageSendRequestId: string;
}

export interface MessageSendFailures {
  createdAt: Generated<string>;
  errorMessage: string;
  id: string;
  kind: string;
  messageSendRequestId: string;
}

export interface MessageSendRequestReplyTargets {
  createdAt: Generated<string>;
  id: string;
  replyToMessageId: string;
  requestId: string;
}

export interface MessageSendRequestRetries {
  createdAt: Generated<string>;
  id: string;
  requestId: string;
  retriedRequestId: string;
}

export interface MessageSendRequests {
  channelId: string;
  content: string;
  createdAt: Generated<string>;
  id: string;
}

export interface MessageSendSkips {
  createdAt: Generated<string>;
  id: string;
  messageSendRequestId: string;
  reason: string;
}

export interface DB {
  backfillRunCompletions: BackfillRunCompletions;
  backfillRunFailures: BackfillRunFailures;
  backfillRunProgress: BackfillRunProgress;
  backfillRuns: BackfillRuns;
  bookmarkAdditions: BookmarkAdditions;
  bookmarkRemovals: BookmarkRemovals;
  bookmarkSnoozes: BookmarkSnoozes;
  channelCategoryChanges: ChannelCategoryChanges;
  channelCategoryClearings: ChannelCategoryClearings;
  channelDetailRevisions: ChannelDetailRevisions;
  channelPositionChanges: ChannelPositionChanges;
  channelPositionClearings: ChannelPositionClearings;
  channelRemovals: ChannelRemovals;
  channels: Channels;
  channelTopicChanges: ChannelTopicChanges;
  channelTopicClearings: ChannelTopicClearings;
  gatewayConnections: GatewayConnections;
  gatewayDisconnections: GatewayDisconnections;
  gatewayHeartbeats: GatewayHeartbeats;
  guilds: Guilds;
  memberDetailRevisions: MemberDetailRevisions;
  members: Members;
  messageDeletions: MessageDeletions;
  messageRevisions: MessageRevisions;
  messages: Messages;
  messageSendDeliveries: MessageSendDeliveries;
  messageSendFailures: MessageSendFailures;
  messageSendRequestReplyTargets: MessageSendRequestReplyTargets;
  messageSendRequestRetries: MessageSendRequestRetries;
  messageSendRequests: MessageSendRequests;
  messageSendSkips: MessageSendSkips;
}
